### ISSUE TITLE
TP Code Review

### ISSUE THREAD

**Issue by rafaelperes** [AY2122S1-CS2113T-T12-2/tp#165]
Hi T12-2. I've some comments about your TP code. 
@leeyikai
1) maybe use enum/static here to avoid magic strings?
![fig1](https://user-images.githubusercontent.com/1132350/139399909-df52ce71-9384-4f31-a582-7a672da4fb09.PNG)

2) same here...
![fig2](https://user-images.githubusercontent.com/1132350/139400130-bd5e9f23-3953-4c92-bcd0-d931a8783084.PNG)

@itsleeqian
1) perhaps improve the abstraction here? it's does not sound like this code snippet belongs to this method...
![fig3](https://user-images.githubusercontent.com/1132350/139400410-11d7d783-ab23-4cab-9414-39d315fc831a.PNG)

2) magic number 3?
![fig4](https://user-images.githubusercontent.com/1132350/139400691-4698a0a0-1c8b-4e73-8f7f-984d5498d005.PNG)

@joshualeeky 
1) maybe check places where magic number/string are presented?
![fig5](https://user-images.githubusercontent.com/1132350/139401429-9544b5e0-edf0-4a72-928e-8c708979c4bf.PNG)

2)This method seems quite long, perhaps you should check slap hard and improve your abstractions?
[SLAP](https://nus-cs2113-ay2122s1.github.io/website/se-book-adapted/chapters/codeQuality.html#slap-hard)
Method:protected static void updateIndividualSpending(Expense expense) {

@lixiyuan416 good use of javadocs

@yeezao
1) maybe check places where magic number and strings might occur?
e.g case "create":  or this magic number 5  Parser.java line 419  String[] newTripInfo = attributesInString.split(" ", 5);

**Comment by yeezao** [comment]
closing v2.1
