### ISSUE TITLE
[PE-D] Hard to read User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-2/tp#172]
The user guide seems to have a formatting problem. The headers and codes are not separated. 
![image.png](https://raw.githubusercontent.com/tryyang2001/ped/main/files/f8830c1e-4336-4828-a900-06aa5caba81b.png)
This causes the user guide very hard to read. 

-------------
Labels: `severity.High` `type.DocumentationBug`
original: tryyang2001/ped#1

**Comment by yeezao** [comment]
fixed through #219
