### ISSUE TITLE
[PE-D] Date Time parsed incorrectly bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-2/tp#187]
![image.png](https://raw.githubusercontent.com/ChrisLangton/ped/main/files/36cd0e7c-1d26-43ce-9eb9-f25267b51003.png)
There is no 29th of Feb in 2021. An exception should be thrown here.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ChrisLangton/ped#4

**Comment by yeezao** [comment]
fixed through #224
