### ISSUE TITLE
[PE-D] Trip that doesn't make sense still can be stored

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-2/tp#188]
![image.png](https://raw.githubusercontent.com/tryyang2001/ped/main/files/7f564ca9-8b06-4212-afa4-7c851c1a2408.png)

For trip that contains a date that is over for a very long time (which does not make sense for now), it still can be stored.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: tryyang2001/ped#7

**Comment by yeezao** [comment]
closed via #219
