### ISSUE TITLE
[Important] DG Tasks

### ISSUE THREAD

**Issue by yeezao** [AY2122S1-CS2113T-T12-2/tp#254]
**Deadlines**
Mon _12 noon_ - DG done
Mon _6 pm_ - Final inspection & submit project

- Yuzhao (Storage, Filestorage) C
- Xi Yuan (Trip, Ui description) AB
- Qi An (Architectural Diagram, Person) D
- Joshua (Parser)
- Yikai (Expense)
- Appendix E together

Sidenote:
- Joshua to check for symbols in diagrams in UG :)

**Comment by lixiyuan416** [comment]
- Yuzhao (Storage, Filestorage)
- Xi Yuan (Trip, Ui description)
- Qi An (Architectural Diagram, Person)
- Joshua (Parser)
- Yikai (Expense)

Sidenote:
- Joshua to check for symbols in diagrams in UG :)
